---
services:
  traefik:
    image: traefik:v3.1
    command:
      - "--providers.docker"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/traefik/:/etc/traefik/

  fastapi-app:
    image: ghcr.io/daniel-mizsak/fastapi-app:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`mlops.top`)"
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.routers.app.tls.certresolver=production"
    deploy:
      mode: replicated
      replicas: 3
    restart: unless-stopped
