---
global:
  checkNewVersion: true
  sendAnonymousUsage: false

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: :443

certificatesResolvers:
  production:
    acme:
      email: your-email@example.com
      storage: /etc/traefik/certs/acme.json
      tlsChallenge: {}

providers:
  docker:
    exposedByDefault: false
