---
global:
  checkNewVersion: true
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: :443

certificatesResolvers:
  staging:
    acme:
      email: info@pythonvilag.hu
      storage: /etc/traefik/certs/acme.json
      tlsChallenge: {}

providers:
  docker:
    exposedByDefault: false
