---
- name: Create system user group.
  ansible.builtin.group:
    name: "{{ user_name }}"
    state: present

- name: Create system user.
  ansible.builtin.user:
    name: "{{ user_name }}"
    shell: /bin/bash
    groups:
      - sudo
      - "{{ user_name }}"
    createhome: true
    state: present

- name: Create SSH directory.
  ansible.builtin.file:
    path: "/home/{{ user_name }}/.ssh"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: "0700"

- name: Add authorized key for user.
  ansible.builtin.copy:
    remote_src: true
    src: /root/.ssh/authorized_keys
    dest: /home/{{ user_name }}/.ssh/authorized_keys
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: "0600"

- name: Add sudo privileges for user.
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    regexp: "^{{ user_name }}"
    line: "{{ user_name }} ALL=(ALL) NOPASSWD:ALL"
    state: present
    validate: "visudo -cf %s"
