---
- name: Install system packages.
  ansible.builtin.apt:
    package:
      - build-essential
      - curl
      - finger
      - nmap
      - python3-pip
      - python3-virtualenv
      - tmux
      - tree
      - zip
    state: present
