---
- name: Deny incoming traffic.
  community.general.ufw:
    default: deny
    direction: incoming

- name: Allow outgoing traffic.
  community.general.ufw:
    default: allow
    direction: outgoing

- name: Allow specific ports.
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
  loop:
    - 22
    - 80
    - 443

- name: Enable UFW.
  community.general.ufw:
    state: enabled
