---
services:
  watchtower:
    image: docker.io/containrrr/watchtower
    command:
      - "--label-enable"
      - "--interval"
      - "30"
      - "--rolling-restart"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  traefik:
    image: docker.io/library/traefik:v3.1
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /traefik/:/etc/traefik/

  fastapi-app:
    image: ghcr.io/daniel-mizsak/fastapi-app:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi-app.rule=Host(`mlops.top`)"
      - "traefik.http.routers.fastapi-app.entrypoints=websecure"
      - "traefik.http.routers.fastapi-app.tls.certresolver=production"
      - "com.centurylinklabs.watchtower.enable=true"
    deploy:
      mode: replicated
      replicas: 3
    restart: unless-stopped
