---
# Configure traefik.
# Documentation:
#   - https://doc.traefik.io/traefik/reference/static-configuration/cli/

global:
  checkNewVersion: true
  sendAnonymousUsage: false
# "--global.checknewversion=false"
# "--global.sendanonymoususage=false"

api:
  dashboard: false
# "--api.dashboard=false"

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
  websecure:
    address: :443
# "--entrypoints.web.address=:80"
# "--entrypoints.web.http.redirections.entrypoint.to=websecure"
# "--entrypoints.websecure.address=:443"

certificatesResolvers:
  production:
    acme:
      email: info@pythonvilag.hu
      storage: /etc/traefik/certs/acme.json
      tlsChallenge: {}
# "--certificatesresolvers.production.acme.email=info@pythonvilag.hu"
# "--certificatesresolvers.production.acme.storage=/etc/traefik/certs/acme.json"
# "--certificatesresolvers.production.acme.tlschallenge=true"

providers:
  docker:
    exposedByDefault: false
# "--providers.docker.exposedbydefault=false"
