---
# https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml

apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    globalArguments:
      - "--global.checknewversion=false"
      - "--global.sendanonymoususage=false"

    ports:
      web:
        redirectTo:
          port: websecure

    additionalArguments:
      - "--certificatesresolvers.production.acme.tlsChallenge=true"
      - "--certificatesresolvers.production.acme.email=info@pythonvilag.hu"
      - "--certificatesresolvers.production.acme.storage=/ssl-certs/acme-production.json"

    persistence:
      enabled: true
      name: ssl-certs
      size: 32Mi
      path: /ssl-certs
